- name: Install package
  apt:
    name: 'coturn'
    state: present

- name: Templating configuration file
  template:
    src: turnserver.conf.j2
    dest: /etc/turnserver.conf
    owner: root
    group: root
   mode: '0644'
  notify: restart coturn
